### ISSUE TITLE
Task List: Repos to fork and populate

### ISSUE THREAD

**Issue by SallyMcGrath** [Migracode-Barcelona/Table-of-Contents#1]
We need to populate the MCB curriculum with all the coursework and tasks we are assigning.

## Steps
1. Fork the matching CYF repo
1. Turn on Issues in settings
1. Add the new repo to [the planner](https://github.com/orgs/Migracode-Barcelona/projects/4/workflows)
1. Run `npx batch-issue-cloner --source CodeYourFuture/Module-NAME --destination Migracode-Barcelona/Module-NAME`

If you get a rate limit warning "submitted too quickly..." then run the command again after a bit. It will backfill any missing issues. 

# Key repo list

- [x] https://github.com/CodeYourFuture/Course-Fundamentals
- [x] https://github.com/CodeYourFuture/Module-HTML-CSS
- [x] https://github.com/CodeYourFuture/Module-JS1
- [x] https://github.com/CodeYourFuture/Module-JS2
- [x] https://github.com/CodeYourFuture/Module-JS3
- [x] https://github.com/CodeYourFuture/JS3-Module-Project/
- [x] https://github.com/CodeYourFuture/Module-Frameworks
- [x] https://github.com/CodeYourFuture/Module-Servers
- [x] https://github.com/CodeYourFuture/Module-Databases
- [x] https://github.com/CodeYourFuture/Full-Stack-Project-Assessment
- [x] https://github.com/CodeYourFuture/Module-The-Launch

**Comment by sairaheta1** [comment]
All repos for the modules have been completed successfully 👍🏼

**Comment by SallyMcGrath** [comment]
Amazing!

@sairaheta1  please approve my pending github bearer token so I can set up https://github.com/Migracode-Barcelona/curriculum

**Comment by sairaheta1** [comment]
@SallyMcGrath Approved!
